language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install requests six flask codecov

script:
  - coverage run tests/Unittest.py

after_success:
  - codecov
