matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      language: python
    - os: linux
      sudo: required
      python: 3.6
      language: python

install:
  - python -m pip install -U pip
  - pip install --upgrade pip
  - pip install requests six flask codecov

script:
  - coverage run tests/Unittest.py

after_success:
  - codecov
