language: python
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
  allow_failures:
    - os: osx
      language: generic 
      env: PYTHON=3.6.4
    

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install python3;
    fi

install:
  - pip install --upgrade pip
  - pip install requests six flask codecov

script:
  - coverage run tests/Unittest.py

after_success:
  - codecov
